### PR TITLE
Half gfx jewels use 26x26 blocks

### PR DESCRIPTION
**Pull request by cxong**
The blocks are small and hard to see at 320x240. Fortunately for jewels mode the grid doesn't fill the screen, which means bigger blocks can be used.

One side effect is that animation speed has been set to block size / 2 again, due to the way animation works. I still would like the slower animation speed, perhaps later we can refactor the animation system to use a 0-1 scalar, which will allow easing functions.

### CODE REVIEW

**Comment by cxong** [comment]
FYI I produced the 26x26 graphics by resizing the 32x32 ones, so if you want you can generate them properly from the SVG source.

**Comment by dorkster** [comment]
I don't like this solution. We should have one block size across the board, and scale it down 50% for HALF_GFX. I think something like 48x48 normal size and 24x24 HALF_GFX size would be appropriate. Unfortunately, I didn't save an xcf of the block graphics, so I'd have to try and recreate them at a higher resolution. Maybe just scaling the blocks image by 1.5 would be satisfactory?

**Comment by cxong** [comment]
That would be easier, but 48x48 normal would mean the normal game will be 13x9 with borders. Is that ok? Alternately, it would be 32x32 for normal, and 16x16/24x24 for half depending on the game mode.

**Comment by dorkster** [comment]
#33 was merged instead of this.

**Pull request closed without merging**
